version: '3.8'

services:
  redis-master:
    image: redis:7.0.5
    container_name: redis-master-ha
    networks:
      redis_net_ha:
        ipv4_address: 172.21.0.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-replica:
    image: redis:7.0.5
    container_name: redis-replica-ha
    networks:
      redis_net_ha:
        ipv4_address: 172.21.0.3
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    volumes:
      - ./redis-rep.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    networks:
      redis_net_ha:
        ipv4_address: 172.21.0.4
    ports:
      - "8080:8080"
    depends_on:
      - redis-master
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  sentinel1:
    image: redis:7.0.5
    container_name: redis-sentinel-ha-1
    networks:
      redis_net_ha:
        ipv4_address: 172.21.0.5
    depends_on:
      - redis-master
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]

  sentinel2:
    image: redis:7.0.5
    container_name: redis-sentinel-ha-2
    networks:
      redis_net_ha:
        ipv4_address: 172.21.0.6
    depends_on:
      - redis-master
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]

  sentinel3:
    image: redis:7.0.5
    container_name: redis-sentinel-ha-3
    networks:
      redis_net_ha:
        ipv4_address: 172.21.0.7
    depends_on:
      - redis-master
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]

  test-app:
    build: .
    container_name: test-app-ha
    networks:
      redis_net_ha:
        ipv4_address: 172.21.0.8
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis-master
      - redis-replica
      - haproxy
    volumes:
      - ./app:/app

networks:
  redis_net_ha:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
